language: ruby
rvm:
- 2.3.0
# source: rubygems
# gem: "bundler"  
# gem: "rspec"    , "~> 2.8.0"
# gem: "rake"     #included if using rake
before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e -a /etc/init.d/xvfb start"
  - sleep 3
env:
  - DB=sqlite3
install:
  - bundle install --path vendor/bundle
script:
  - RAILS_ENV=test bundle exec rake --trace
after_success:
- coveralls
