language: ruby
rvm:
- 2.0.0
- 2.1.0
- 2.1.3
# source: rubygems
# gem: "bundler"  
# gem: "rspec"    , "~> 2.8.0"
# gem: "rake"     #included if using rake
env:
  - DB=sqlite3
install:
  - bundle install --path vendor/bundle
script:
  - RAILS_ENV=test bundle exec rake --trace