language: ruby
rvm:
- 2.0.0
- 2.1.0
- 2.1.3
source: rubygems
gem "bundler"  , "~> 1.1.3"
gem "rspec"    , "~> 2.8.0"
gem "rake"     , "~> 0.9.2.2" #included if using rake
task :default => [:spec]
desc 'run Rspec specs'
task :spec do
  sh 'rspec spec'
end
RAILS_ENV=test
RACK_ENV=test